version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-dev
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # Servicios externos
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1           # Habilitar persistencia
      - SKIP_SSL_CERT_DOWNLOAD=1
    volumes:
      - "./localstack-data:/var/lib/localstack"  # Cambiar ruta de montaje
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    